from internal.vector2 import Vector2


# World Configs
LINE_UP = '\033[1A'
LINE_CLEAR = '\x1b[2K'
TARGET_FRAMERATE = 1/60
CANVAS_SIZE = Vector2(1200, 800)
SECTOR_SIZE = Vector2(100, 100)
TEXT_COLOR = "teal"

STARTING_PLANTS = 15
SECTOR_BLUR_LEVEL = 2
SECTOR_MAX_FRAMES_BETWEEN_SMOOTH = 10
SECTOR_REGEN_RATE = 0.1
SECTOR_DECAY_RATE = 0.01
MIN_AREA_CALC_PRECISION = 4
MAX_AREA_CALC_PRECISION = 8
ALERT_LIFETIME = 5


# Plant Configs
OPTIMAL_PLANT_COLOR = (0, 200, 0)
PLANT_NUTRIENT_EFFICIENCY = 2
SEED_DRAG = 0.25
SEED_DENSITY = 1.0
SEED_SIZE_FACTOR = 0.1
SEED_COST_FACTOR = 0.1
MUTATION_CHANCE = 0.25
MUTATION_FACTOR = 0.25
MUTATION_CENTER_WEIGHTING = 5


# Plant Genome Configs
MIN_PLANT_RADIUS = 5.0
MAX_PLANT_RADIUS = 50.0
MAX_GROWTH_SPEED = 5.0
MAX_SEED_SPEED = 100.0
MIN_LIFESPAN = 30.0
MAX_LIFESPAN = 300.0



# Derived values, do not edit
areaCalcPrecision = MAX_AREA_CALC_PRECISION
maxTimeBetweenSectorSmoothing = TARGET_FRAMERATE * SECTOR_MAX_FRAMES_BETWEEN_SMOOTH